"""Real (LLM-backed) proposal draft generation, replacing
`mock_store.draft_proposal()`'s static template. See docs/architecture.md
14.5 — this is the first genuinely generative-AI feature in `backend/`.

Scope (2026-07-05, text-only v1): gathers real internal history for the
named customer via the same Provider/Evidence pipeline
`reasoning_pipeline.py` uses (`fetch_required_data` ->
`integrate_evidence` -> `interpret_evidence`), and asks Claude to draft
proposal text grounded in that history. Explicitly NOT implemented:
external trend research (web search), image sourcing/illustration — see
docs/architecture.md 14.5 for why these are deferred.

IMPORTANT (fixed 2026-07-05, same day as introduced): the first version of
this module called `LogsysProvider().fetch(...)` directly instead of
going through `fetch_required_data`/`integrate_evidence`. That bypassed
`evidence_integration.py`'s `_dedupe_records()` step, so raw
`purchase_orders` rows (which can contain many rows sharing the same
案件名/顧客名/ステータス/顧客納品日, differing only in fields not
selected — e.g. per-line-item detail) went straight to the LLM prompt
undeduplicated: a real end-to-end test surfaced ten identical
"20211203US発注分" lines in `internal_history_used`. Always route through
the same Evidence pipeline as `reasoning_pipeline.py` and `_q5_project_lookup`
— do not re-implement a second, parallel (and less correct) data-fetch
path.

Governance: proposal drafts are customer-facing content generated by an
LLM from real (but possibly incomplete) internal data, and are NOT backed
by the same kind of verifiable Provider-only Evidence pipeline
`reasoning_pipeline.py` uses for its own answers (an LLM still composes
free text from the evidence, unlike reasoning_pipeline's fixed templates)
— it could contain confident-sounding but wrong claims. Every draft is
therefore submitted to the Governance queue at `governance_level="high"`
(never auto-approved, per the Blueprint Chapter 11 Approval Levels table)
before it should be considered a finished draft a salesperson can send
out.
"""
from __future__ import annotations

from typing import Any
from uuid import uuid4

from capability.domain import Capability, CapabilityStatus, ExecutionStatus, GovernanceLevel
from services.capability_instance import ensure_registered, registry as capability_registry
from services import governance_store
from services.data_providers import fetch_required_data
from services.evidence_integration import integrate_evidence
from services.evidence_interpreter import interpret_evidence
from services.llm_client import generate_text, generate_text_with_web_search, generate_image
from services.trace_store import save_trace

from pathlib import Path

GENERATED_IMAGES_DIR = Path(__file__).resolve().parents[1] / "data" / "generated_proposal_images"

PROPOSAL_DRAFT_CAPABILITY = Capability(
    capability_id="proposal_draft_generation",
    name="Customer Proposal Draft Generation",
    category="business",
    description=(
        "Drafts a customer-facing sales proposal using an LLM grounded in "
        "real internal purchase-order/sales history for the named "
        "customer. Text-only v1: no external trend research or image "
        "sourcing yet (see docs/architecture.md 14.5). Always requires "
        "human review via Governance before being sent to a customer."
    ),
    owner_team="AI OS",
    owner_user_id="system",
    team_id="ai-os",
    status=CapabilityStatus.DEPLOYED,
    version="1.0.0",
    supported_inputs=["customer", "purpose"],
    supported_outputs=["proposal_draft"],
    required_context=["purchase_orders"],
    governance_level=GovernanceLevel.HIGH,
)


def _gather_internal_history(customer: str) -> str:
    """Real internal history for this customer, formatted for the LLM
    prompt. Uses the same Evidence pipeline as `reasoning_pipeline.py`
    (`fetch_required_data` -> `integrate_evidence` -> `interpret_evidence`)
    so deduplication and display-sampling behave identically everywhere
    in the codebase, not as a second, separately-maintained implementation.

    Returns an explicit "not found" note rather than fabricating context
    if nothing matches — the LLM prompt instructs Claude to treat this
    note as ground truth, not as license to invent history.
    """
    try:
        evidence_list = fetch_required_data([
            {"priority": 1, "item": f"{customer}の案件検索", "provider": "logsys",
             "dataset": "projects", "params": {"keyword": customer}},
        ])
        integrated = interpret_evidence(integrate_evidence(evidence_list))
        evidence = integrated[0] if integrated else {}

        if evidence.get("status") != "ok":
            return f"「{customer}」に関する社内の過去案件データは見つかりませんでした。"

        records = evidence.get("display_records") or []
        total = evidence.get("record_count", len(records))
        if not records:
            return f"「{customer}」に関する社内の過去案件データは見つかりませんでした。"

        lines = [
            f"- {r.get('案件名', '(不明)')} (ステータス: {r.get('ステータス', '不明')})"
            for r in records
        ]
        sample_note = f"（重複排除後、先頭{len(records)}件を表示）" if total > len(records) else ""
        return f"過去{total}件中の直近案件{sample_note}:\n" + "\n".join(lines)
    except Exception as e:
        return f"社内履歴の取得に失敗しました（エラー: {e}）。このドラフトは履歴データなしで作成されています。"


def draft_proposal(
    customer: str, purpose: str, include_external: bool = False, include_image: bool = False,
) -> dict[str, Any]:
    """Generate a proposal draft and submit it for Governance review.

    Returns immediately with the draft text and a `governance_approval_id`
    — the draft is NOT considered finished/sendable until a human approves
    it via `POST /governance/{id}/decide` (this capability's
    governance_level is HIGH, so it is never auto-approved).

    `include_external=True` enables Claude's web search tool for real
    industry/trend research about the customer (2026-07-05, closing the
    gap flagged in docs/architecture.md 14.5). This makes the draft
    depend on live, uncontrolled external content rather than only
    Provider-fetched internal data, so it is reported separately
    (`external_sources`) — a human reviewing the draft can see exactly
    which URLs were used and judge them, rather than trusting prose that
    doesn't say where a claim came from.

    `include_image=True` generates one supporting image via OpenAI's
    `gpt-image-1` (2026-07-05), derived from the customer/purpose text.
    The image is saved to disk (not embedded as base64 in the response —
    that string is enormous and useless to pass around); only its path is
    returned. This is a simple v1: no attempt is made to match the image
    to the drafted text's actual content, and no OCR/vision check
    confirms it's on-topic — a human reviewing the draft should look at
    the image itself, not just trust that it's relevant.
    """
    ensure_registered(PROPOSAL_DRAFT_CAPABILITY)
    trace_id = f"proposal-{uuid4().hex[:8]}"
    execution = capability_registry.execute_capability(
        capability_id=PROPOSAL_DRAFT_CAPABILITY.capability_id,
        inputs={
            "customer": customer, "purpose": purpose,
            "include_external": include_external, "include_image": include_image,
        },
        user_id="system",
        project_id="",
        trace_id=trace_id,
    )

    internal_history = _gather_internal_history(customer)

    external_instruction = (
        "外部の業界動向・市場トレンド・顧客企業の公開情報について、Web検索で調査し、"
        "提案書に反映してください。調査した内容には必ず出典（検索結果）が伴います。"
        if include_external else
        "外部トレンド調査・顧客の業界動向は現時点で未対応です。含めないでください。"
    )

    prompt = f"""あなたはB2B営業支援AIです。以下の情報をもとに、顧客向け提案書のドラフトを作成してください。

顧客名: {customer}
提案の目的: {purpose}

社内の過去案件履歴（これが唯一の社内事実情報です。ここにない情報を社内事実として書かないでください）:
{internal_history}

以下の構成で、日本語で提案書ドラフトを作成してください:
1. 顧客の課題（社内履歴{"および外部調査結果" if include_external else ""}から読み取れる範囲。推測を含む場合は「推測」と明記）
2. 提案内容
3. 期待される効果
4. 実行計画

重要な制約:
- {external_instruction}
- 社内履歴に無い具体的な数値・固有名詞を断定的に書かないでください。不明な点は「要確認」と明記してください。"""

    external_sources: list[str] = []
    try:
        if include_external:
            draft_text, external_sources = generate_text_with_web_search(prompt, max_tokens=3000, feature="proposal_draft")
        else:
            draft_text = generate_text(prompt, max_tokens=2000, feature="proposal_draft")
    except Exception as e:
        capability_registry.record_execution_result(
            execution_id=execution.execution_id, outputs={},
            status=ExecutionStatus.FAILED, error_message=str(e),
        )
        raise

    # 画像生成機能は2026-07-05に停止（ビジネス判断: 画像は各ユーザーが個別に
    # 生成AIツールを使う方針とし、このプラットフォームの機能としては提供しない）。
    # `include_image=True` が渡されても意図的に何もしない。実装コード
    # (generate_image, GENERATED_IMAGES_DIR) 自体は将来の再有効化に備えて
    # 削除せず残してある。docs/architecture.md 14.7 参照。
    image_path: str | None = None
    if include_image:
        pass

    capability_registry.record_execution_result(
        execution_id=execution.execution_id,
        outputs={
            "draft_length": len(draft_text),
            "external_sources_count": len(external_sources),
            "image_generated": image_path is not None,
        },
        status=ExecutionStatus.COMPLETED,
    )

    try:
        save_trace(trace_id, {
            "customer": customer, "purpose": purpose, "include_external": include_external,
            "internal_history": internal_history, "draft_text": draft_text,
            "external_sources": external_sources, "image_path": image_path,
        })
    except Exception:
        pass

    approval = governance_store.submit_proposal(
        source_capability_id=PROPOSAL_DRAFT_CAPABILITY.capability_id,
        concept=f"提案書ドラフト: {customer} 向け「{purpose}」",
        ai_hypothesis=draft_text,
        confidence_score=0.6,
        trace_id=trace_id,
        governance_level=PROPOSAL_DRAFT_CAPABILITY.governance_level.value,
    )

    note_parts = ["このドラフトはAI生成です。"]
    if not include_external:
        note_parts.append("外部調査は含まれていません。")
    note_parts.append(
        "画像生成機能は現在無効化されています（個別に生成AIツールをご利用ください）。"
    )
    note_parts.append("Governance承認前は顧客への送付不可です。")

    return {
        "customer": customer,
        "purpose": purpose,
        "draft_text": draft_text,
        "internal_history_used": internal_history,
        "external_sources": external_sources,
        "image_path": image_path,
        "trace_id": trace_id,
        "governance_approval_id": approval.approval_id,
        "status": approval.status,
        "note": "".join(note_parts),
    }